In [2]:
"""Count The Number Of Times Each Value Appears In An Array Of Integers"""

'Count The Number Of Times Each Value Appears In An Array Of Integers'

In [9]:
import numpy as np
from collections import Counter
arr1=np.random.randint(1,10,24)
arr1=sorted(arr1)
print(arr1)
print(Counter(arr1))

[1, 1, 1, 1, 1, 1, 2, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 7, 7, 7, 9, 9, 9]
Counter({1: 6, 4: 4, 5: 4, 7: 3, 9: 3, 3: 2, 2: 1, 6: 1})


In [10]:
"""2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function."""

'2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function.'

In [13]:
arr2=np.random.randint(1,10,9)
print(arr2)
print(arr2.reshape(3,3))

[1 1 7 7 8 4 1 1 7]
[[1 1 7]
 [7 8 4]
 [1 1 7]]


In [14]:
"""3. How to find the memory size of any array"""

'3. How to find the memory size of any array'

In [16]:
arr3=np.random.randint(2,30,12)
print(arr3.nbytes)


48


In [17]:
"""4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside."""

'4. Create a 2d array of size 10 by 10 with 1 on the border and 0 inside.'

In [19]:
arr4 = np.ones((10,10))
arr4[1:-1, 1:-1] = 0
print(arr4)



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [20]:
"""5.Create a 8x8 matrix and fill it with a checkerboard pattern."""

'5.Create a 8x8 matrix and fill it with a checkerboard pattern.'

In [33]:
arr5 = np.ones((8,8))
for i in range(arr5.shape[0]):
    for j in range(arr5.shape[0]):
        #print(i,j)
        if (i+j)%2==0:
            arr5[i][j]=0
print(arr5)


arr5_2 = np.zeros((8,8))
arr5_2[1::2,::2] = 1
arr5_2[::2,1::2] = 1
    

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [26]:
"""6.Normalize a 5x5 random matrix"""

'6.Normalize a 5x5 random matrix'

In [31]:
a = np.random.random((5,5))
b= (a - a.min())/(a.std(axis=0))
b

array([[1.16481588, 0.96542693, 2.84757817, 2.54391147, 1.17600671],
       [0.        , 2.75368815, 1.29874353, 0.02497584, 3.15092601],
       [3.05309435, 3.03402475, 4.14230459, 0.57222418, 0.34049127],
       [1.97674408, 0.54452008, 1.82676549, 2.21281072, 1.66271311],
       [1.45031983, 2.43402978, 3.12998442, 0.57196277, 0.56654754]])

In [32]:
"""7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place."""

'7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place.'

In [43]:
arr7=np.random.randint(0,11,30)
print(arr7)
m=np.where((arr7 > 3) & (arr7 <8))
arr7[m]*=-1
print(arr7)



[ 2  4  1  9  8  5  6  3 10  3  4  8  5  1  5  2  2  4  2  0  1  0  5  9
  7 10  6  1  7  0]
[ 2 -4  1  9  8 -5 -6  3 10  3 -4  8 -5  1 -5  2  2 -4  2  0  1  0 -5  9
 -7 10 -6  1 -7  0]


In [51]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-02-13
Today:  2020-02-14
Tomorrow:  2020-02-15


In [44]:
"""9. Generate two arrays of size 2X4 & 3X3, find difference between them."""

'9. Generate two arrays of size 2X4 & 3X3, find difference between them.'

In [59]:
arr8 =np.random.randint(10,size=(2,4))
arr8.reshape(2,1,4)
arr9=np.random.randint(10,size=(3,3))
arr9.reshape(1,3,3)
arr8 - arr9

ValueError: operands could not be broadcast together with shapes (2,4) (3,3) 

In [52]:
"""
10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?

['cat','cat',...,'rat','dog','dog','cat'...]
"""

"\n10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?\n\n['cat','cat',...,'rat','dog','dog','cat'...]\n"

In [55]:
arr10=np.random.randint(0,3,100)
print(arr10)
np.choose(arr10, choices=['cat','dog','rat'])

[1 1 2 1 1 1 1 1 0 1 2 1 0 2 1 2 0 1 1 1 1 1 1 1 2 0 0 0 0 0 1 2 1 0 1 2 2
 1 2 2 2 0 2 1 2 0 2 0 0 1 2 1 0 1 1 0 1 2 0 0 2 1 2 2 0 1 2 2 1 2 2 1 0 1
 2 1 2 2 0 0 1 1 0 2 2 1 1 2 1 2 2 2 2 0 1 0 0 0 1 0]


array(['dog', 'dog', 'rat', 'dog', 'dog', 'dog', 'dog', 'dog', 'cat',
       'dog', 'rat', 'dog', 'cat', 'rat', 'dog', 'rat', 'cat', 'dog',
       'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'rat', 'cat', 'cat',
       'cat', 'cat', 'cat', 'dog', 'rat', 'dog', 'cat', 'dog', 'rat',
       'rat', 'dog', 'rat', 'rat', 'rat', 'cat', 'rat', 'dog', 'rat',
       'cat', 'rat', 'cat', 'cat', 'dog', 'rat', 'dog', 'cat', 'dog',
       'dog', 'cat', 'dog', 'rat', 'cat', 'cat', 'rat', 'dog', 'rat',
       'rat', 'cat', 'dog', 'rat', 'rat', 'dog', 'rat', 'rat', 'dog',
       'cat', 'dog', 'rat', 'dog', 'rat', 'rat', 'cat', 'cat', 'dog',
       'dog', 'cat', 'rat', 'rat', 'dog', 'dog', 'rat', 'dog', 'rat',
       'rat', 'rat', 'rat', 'cat', 'dog', 'cat', 'cat', 'cat', 'dog',
       'cat'], dtype='<U3')

In [60]:
"""
11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values"""

'\n11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values'

In [63]:
v = np.linspace(0,1,10)[1:-1]
print(v)

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


In [64]:
"""12.Given a two dimensional array, how to extract unique rows?"""

'Given a two dimensional array, how to extract unique rows?'

In [70]:
arr12=np.array([[1,5,8,9],[1,2,5,2],[1,5,8,9]])
unique_row=np.unique(arr12,axis=0)
print(unique_row)

[[1 2 5 2]
 [1 5 8 9]]


In [71]:
"""13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area"""

'13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area'

In [73]:
"""14.How to find the closest value (to a given scalar) in a vector?"""

'14.How to find the closest value (to a given scalar) in a vector?'

In [82]:
arr14 = np.arange(100)
x = 10.31
i= (np.abs(arr14-x)).argmin()
print(arr14[i])

10


In [ ]:
"""15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance."""

In [83]:
a= np.random.random((10,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.31772717 0.40716793 0.57074312 0.53251155 0.36427889
  0.15169513 0.36493007 0.24554892 0.36634445]
 [0.31772717 0.         0.36317063 0.29359072 0.65270318 0.54434824
  0.43709512 0.61496446 0.26900229 0.63762466]
 [0.40716793 0.36317063 0.         0.63301419 0.33131549 0.31083118
  0.39736822 0.44319028 0.16265048 0.76599933]
 [0.57074312 0.29359072 0.63301419 0.         0.94182358 0.83783271
  0.71043527 0.90237063 0.56166417 0.80721571]
 [0.53251155 0.65270318 0.33131549 0.94182358 0.         0.18090641
  0.42149414 0.29130771 0.38576765 0.80284392]
 [0.36427889 0.54434824 0.31083118 0.83783271 0.18090641 0.
  0.24185208 0.14349849 0.28113277 0.62254754]
 [0.15169513 0.43709512 0.39736822 0.71043527 0.42149414 0.24185208
  0.         0.21451538 0.26244037 0.39276645]
 [0.36493007 0.61496446 0.44319028 0.90237063 0.29130771 0.14349849
  0.21451538 0.         0.37610791 0.53559695]
 [0.24554892 0.26900229 0.16265048 0.56166417 0.38576765 0.28113277
  0.26244037 0.37610

In [84]:
"""16. How to sort an array by the nth column?"""

'16. How to sort an array by the nth column?'

In [92]:
arr16 = np.random.randint(0,10,(5,5))
n=3
print(arr16[arr16[:,1].argsort()])

[[4 4 9 8 0]
 [1 4 3 4 4]
 [5 6 8 2 0]
 [6 8 3 0 4]
 [2 8 7 3 7]]


In [ ]:
"""17.How to tell if a given 2D array has null columns?"""

In [94]:
arr17= np.random.randint(0,9,(3,3))
print((~arr17.any(axis=0)).any())

False


In [ ]:
"""18. Considering a two dimensions array, how to get sum over the last two columns at once?"""

In [97]:
A = np.random.randint(0,20,(5,4))
print(A)
sum1 = A.reshape(A.shape[:-2] + (-1,)).sum(axis=0)
print(sum1)

[[ 2 19 14 12]
 [ 9 11 18  2]
 [17 13 14  1]
 [13  0  2  1]
 [12  3  4  8]]
175


In [ ]:
"""
20. Given a 1d array(size 100) of boolean values, identify total number of True in it.¶
"""

In [119]:
arr4 = np.ones((10,10))
arr4[1:-1, 1:-1] = 0
print(arr4)
count=0
for i in range(arr4.shape[0]):
    for j in range(arr4.shape[0]):
        if arr4[i][j].any():
            count+=1
print(count)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
36


In [101]:
"""21. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?"""

'21. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?'

In [102]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [104]:
"""22. How to swap two rows of an array?"""

'22. How to swap two rows of an array?'

In [105]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
"""
24. How to get n largest value of an array?"""

In [109]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 2
print (Z[np.argsort(Z)[-n:-n+1]])

[9998]


In [110]:
"""25. Given two random arrays of shape 5X5, identify the common elements between them."""

'25. Given two random arrays of shape 5X5, identify the common elements between them.'

In [111]:
import numpy as np
array1 = np.random.randint(0,9,(5,5))
array2 = np.random.randint(0,9,(5,5))
print(np.intersect1d(array1, array2))

[0 1 2 3 4 5 6 7]


In [114]:
"""26. How to get index of top two highest value in a 1d array?"""
Z = np.arange(10000)
np.random.shuffle(Z)
print (Z[np.argsort(Z)[-2:]])

[0 1 2 3 4 5 6 7 8 9]
[9998 9999]
